name: Create Provenance
on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  provenance:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
      - run: npm pack
      - uses: actions/attest-build-provenance@v1
        with:
          subject-path: "*.tgz"
      - name: Update Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: "*.tgz"
